name: FindLaw Repository Checks

# Runs on repo creation or manually from the Actions tab
on:
  create:
  fork:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: FindLaw Repository Check Job
    steps:
      - uses: actions/checkout@v2

      # TODO double check the regex
      - name: "Check FindLaw Repository Name1"
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.repository.name }}
          regex: ^(.*)$
          flags: gm
      - if: true
        run: echo ${{ steps.regex-match.inputs.regex }}--${{ steps.regex-match.outputs.group1 }}--${{ steps.regex-match.outputs.match }}
        
      - name: "Check FindLaw Repository Name2"
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.repository.name }}
          regex: '^(.*)$'
          flags: gm
      - if: true
        run: echo ${{ steps.regex-match.inputs.regex }}--${{ steps.regex-match.outputs.group1 }}--${{ steps.regex-match.outputs.match }}
        
      - name: "Check FindLaw Repository Name3"
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.repository.name }}
          regex: '(.+)'
          flags: gm
      - if: true
        run: echo ${{ steps.regex-match.inputs.regex }}--${{ steps.regex-match.outputs.group1 }}--${{ steps.regex-match.outputs.match }}
        
      - name: "Check FindLaw Repository Name4"
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.repository.name }}
          regex: '(FindLaw_.*)'
          flags: gm
      - if: true
        run: echo ${{ steps.regex-match.inputs.regex }}--${{ steps.regex-match.outputs.group1 }}--${{ steps.regex-match.outputs.match }}
